Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2024-05-28 13:51:16,329 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-05-28 13:51:19,469 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.springframework.core.io.DefaultResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,470 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.springframework.core.io.ResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,473 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.apache.tools.ant.Task: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,502 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.springframework.core.io.Resource: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,513 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index jakarta.jms.XAConnection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,513 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index jakarta.jms.XASession: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,514 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index jakarta.jms.XAConnectionFactory: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,515 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index jakarta.jms.Connection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,537 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index io.mashona.logwriting.ArrayStore: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,540 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.apache.activemq.artemis.core.journal.RecordInfo: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:19,541 WARN  [io.qua.dep.ind.IndexWrapper] (build-69) Failed to index org.apache.activemq.artemis.core.journal.Journal: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@74518890
2024-05-28 13:51:22,339 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 5401ms
Server configuration updated and persisted. Run the following command to review the configuration:
	kc.sh show-config
Next time you run the server, just run:
	kc.sh start --optimized
2024-05-28 13:51:23,040 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-05-28 13:51:23,483 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: auth-test-v2.vizeo.eu, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: https://auth-test-v2.vizeo.eu, Admin: auth-test-v2.vizeo.eu, Port: -1, Proxied: true
2024-05-28 13:51:23,689 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-05-28 13:51:23,773 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-05-28 13:51:23,849 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-05-28 13:51:23,852 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: df58bd5e-ef0a-4bda-9d37-e1ae062ec7aa, name: 58a74ea52dc8-21605
2024-05-28 13:51:23,857 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-28 13:51:23,857 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2024-05-28 13:51:23,858 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-28 13:51:23,858 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2024-05-28 13:51:23,863 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.18076
2024-05-28 13:51:24,952 INFO  [io.agroal.pool] (JPA Startup Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
2024-05-28 13:51:25,572 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-05-28 13:51:25,577 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-05-28 13:51:25,868 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 58a74ea52dc8-21605: no members discovered after 2002 ms: creating cluster as coordinator
2024-05-28 13:51:25,891 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [58a74ea52dc8-21605|0] (1) [58a74ea52dc8-21605]
2024-05-28 13:51:25,924 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `58a74ea52dc8-21605`, physical addresses are `[172.18.0.29:33612]`
2024-05-28 13:51:25,933 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-05-28 13:51:26,205 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 58a74ea52dc8-21605, Site name: null
2024-05-28 13:51:26,949 INFO  [io.quarkus] (main) Keycloak 24.0.4 on JVM (powered by Quarkus 3.8.4) started in 4.391s. Listening on: http://0.0.0.0:8180
2024-05-28 13:51:26,949 INFO  [io.quarkus] (main) Profile prod activated. 
2024-05-28 13:51:26,949 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-05-28 13:53:06,939 INFO  [org.infinispan.CLUSTER] (Thread-31) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-05-28 13:53:06,957 INFO  [io.quarkus] (Shutdown thread) Keycloak stopped in 0.031s
2024-05-28 13:53:44,344 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-05-28 13:53:44,801 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: auth-test-v2.vizeo.eu, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: https://auth-test-v2.vizeo.eu, Admin: auth-test-v2.vizeo.eu, Port: -1, Proxied: true
2024-05-28 13:53:45,002 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-05-28 13:53:45,090 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-05-28 13:53:45,170 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-05-28 13:53:45,173 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 9a2390a6-8f31-4e8a-99c7-f836619aadf7, name: 58a74ea52dc8-47841
2024-05-28 13:53:45,179 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-28 13:53:45,179 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2024-05-28 13:53:45,179 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-28 13:53:45,179 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2024-05-28 13:53:45,185 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.43516
2024-05-28 13:53:46,231 INFO  [io.agroal.pool] (JPA Startup Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
2024-05-28 13:53:46,850 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-05-28 13:53:46,855 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-05-28 13:53:47,191 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 58a74ea52dc8-47841: no members discovered after 2004 ms: creating cluster as coordinator
2024-05-28 13:53:47,196 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [58a74ea52dc8-47841|0] (1) [58a74ea52dc8-47841]
2024-05-28 13:53:47,207 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `58a74ea52dc8-47841`, physical addresses are `[172.18.0.29:59052]`
2024-05-28 13:53:47,213 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-05-28 13:53:47,493 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 58a74ea52dc8-47841, Site name: null
2024-05-28 13:53:48,261 INFO  [io.quarkus] (main) Keycloak 24.0.4 on JVM (powered by Quarkus 3.8.4) started in 4.399s. Listening on: http://0.0.0.0:8180
2024-05-28 13:53:48,262 INFO  [io.quarkus] (main) Profile prod activated. 
2024-05-28 13:53:48,262 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-05-28 14:10:06,087 WARN  [org.keycloak.events] (executor-thread-2) type="REFRESH_TOKEN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="e03c3428-68e5-4bae-b762-fec019a9bb84", sessionId="fc0b621f-b0aa-4f03-9978-e165af87dd07", ipAddress="41.216.98.178", error="invalid_token", reason="Session not active", grant_type="refresh_token", refresh_token_type="Refresh", refresh_token_id="6cf40a2b-781f-4bc8-bfa8-8276dfb77153", client_auth_method="client-secret"
2024-05-28 14:18:12,339 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-8) Using deprecated 'credentials' format in JSON representation for user 'TOTO'. It will be removed in future versions
2024-05-28 14:18:12,340 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-28 14:19:28,207 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-8) Using deprecated 'credentials' format in JSON representation for user 'djdjd'. It will be removed in future versions
2024-05-28 14:19:28,208 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-29 00:10:03,431 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-05-29 03:40:58,894 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-05-29 06:03:15,041 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-05-29 09:40:27,438 WARN  [org.keycloak.events] (executor-thread-27) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="80.214.145.170", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="6cc1c429-d698-42c5-95ad-9a395cf18219", username="contact@rchabitat.fr"
2024-05-29 09:40:49,358 WARN  [org.keycloak.events] (executor-thread-27) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="80.214.145.170", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="6cc1c429-d698-42c5-95ad-9a395cf18219", username="contact@rchabitat.fr"
2024-05-29 09:41:16,678 WARN  [org.keycloak.events] (executor-thread-27) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="80.214.145.170", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="6cc1c429-d698-42c5-95ad-9a395cf18219", username="dpsmarket69"
2024-05-29 11:50:46,602 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-05-29 15:39:06,234 WARN  [org.keycloak.events] (executor-thread-27) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="null", userId="null", ipAddress="80.214.220.246", error="cookie_not_found"
2024-05-29 18:02:25,538 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-05-29 18:11:53,980 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-05-29 23:56:11,240 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-05-30 06:09:18,136 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-05-30 08:16:48,004 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-05-30 09:03:37,831 WARN  [org.keycloak.events] (executor-thread-36) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="null", userId="null", ipAddress="80.214.219.176", error="cookie_not_found"
2024-05-30 12:01:37,371 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-05-30 16:28:27,361 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-05-30 17:18:15,254 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-41) Using deprecated 'credentials' format in JSON representation for user 'TOTO'. It will be removed in future versions
2024-05-30 17:18:15,254 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-41) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-30 17:19:32,305 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-41) Using deprecated 'credentials' format in JSON representation for user 'djdjd'. It will be removed in future versions
2024-05-30 17:19:32,306 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-41) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-30 17:30:50,822 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-48) Using deprecated 'credentials' format in JSON representation for user 'TOTO'. It will be removed in future versions
2024-05-30 17:30:50,822 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-48) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-30 17:32:30,138 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-48) Using deprecated 'credentials' format in JSON representation for user 'djdjd'. It will be removed in future versions
2024-05-30 17:32:30,139 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-48) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-30 18:04:32,233 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-05-30 22:53:08,535 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-05-30 23:48:57,052 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-05-31 00:14:14,188 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-05-31 01:19:52,199 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-05-31 03:46:26,558 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-05-31 06:17:06,684 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-05-31 06:38:46,824 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-05-31 11:51:13,238 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-05-31 16:25:28,338 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-05-31 17:54:32,661 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-05-31 23:53:25,821 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-01 02:17:03,235 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-1) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-01 05:57:22,777 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-01 09:44:05,866 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-01 09:57:13,686 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-01 11:45:08,744 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-01 18:02:40,230 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-02 00:18:58,613 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-02 00:19:04,096 WARN  [org.keycloak.events] (executor-thread-82) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="null", userId="null", ipAddress="120.24.50.224", error="cookie_not_found"
2024-06-02 01:38:35,265 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-02 06:06:32,259 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-02 11:58:49,670 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-02 13:19:14,788 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-02 14:04:36,264 INFO  [org.infinispan.CLUSTER] (Thread-31) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-06-02 14:04:36,291 INFO  [io.quarkus] (Shutdown thread) Keycloak stopped in 0.044s
2024-06-02 14:04:38,565 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-06-02 14:04:39,042 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: auth-test-v2.vizeo.eu, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: https://auth-test-v2.vizeo.eu, Admin: auth-test-v2.vizeo.eu, Port: -1, Proxied: true
2024-06-02 14:04:39,256 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-06-02 14:04:39,342 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-06-02 14:04:39,428 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-06-02 14:04:39,433 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 0c71491f-3330-419c-8bd4-e5d21187f55b, name: 58a74ea52dc8-8603
2024-06-02 14:04:39,440 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-06-02 14:04:39,440 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2024-06-02 14:04:39,440 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-06-02 14:04:39,440 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2024-06-02 14:04:39,446 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.30892
2024-06-02 14:04:40,496 INFO  [io.agroal.pool] (JPA Startup Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
2024-06-02 14:04:41,151 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-06-02 14:04:41,156 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-06-02 14:04:41,450 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 58a74ea52dc8-8603: no members discovered after 2001 ms: creating cluster as coordinator
2024-06-02 14:04:41,458 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [58a74ea52dc8-8603|0] (1) [58a74ea52dc8-8603]
2024-06-02 14:04:41,469 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `58a74ea52dc8-8603`, physical addresses are `[172.18.0.29:46428]`
2024-06-02 14:04:41,476 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-06-02 14:04:41,748 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 58a74ea52dc8-8603, Site name: null
2024-06-02 14:04:42,504 INFO  [io.quarkus] (main) Keycloak 24.0.4 on JVM (powered by Quarkus 3.8.4) started in 4.402s. Listening on: http://0.0.0.0:8180
2024-06-02 14:04:42,504 INFO  [io.quarkus] (main) Profile prod activated. 
2024-06-02 14:04:42,504 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-06-02 14:06:40,541 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2024-06-02 14:06:40,541 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2024-06-02 14:06:40,541 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2024-06-02 14:06:40,541 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2024-06-02 14:06:40,542 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
2024-06-02 14:35:11,379 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-02 17:53:19,102 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-03 00:03:44,960 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-03 05:00:08,738 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-03 06:07:43,594 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-03 07:07:09,635 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-03 08:08:23,467 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-7) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-03 12:23:21,049 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-03 16:29:56,686 WARN  [org.keycloak.events] (executor-thread-8) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="742fcead-d8c7-4455-b89b-329b5ad6e7be", ipAddress="102.22.172.189", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="csagbo"
2024-06-03 16:30:24,030 WARN  [org.keycloak.events] (executor-thread-8) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="742fcead-d8c7-4455-b89b-329b5ad6e7be", ipAddress="102.22.172.189", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="csagbo"
2024-06-03 16:33:22,979 WARN  [org.keycloak.events] (executor-thread-18) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="0f279dc9-88c4-4e6c-a203-531dbba5832c", ipAddress="102.22.172.189", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="julien"
2024-06-03 16:46:36,837 WARN  [org.keycloak.events] (executor-thread-25) type="REFRESH_TOKEN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="null", ipAddress="102.22.172.189", error="invalid_token", reason="Token is not active", grant_type="refresh_token", client_auth_method="client-secret"
2024-06-03 18:05:52,853 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-03 21:23:23,946 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-04 00:04:14,226 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-04 05:59:16,659 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-04 12:09:36,888 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-04 15:13:51,452 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-8) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-04 18:11:23,082 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-05 00:22:26,598 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-05 05:52:26,065 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-05 05:53:29,843 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-05 12:08:26,086 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-05 12:35:40,195 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-05 18:00:51,658 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-06 00:02:22,626 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-06 02:07:52,391 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-06 02:11:47,063 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-06 06:01:39,607 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-06 08:40:56,604 WARN  [org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor] (executor-thread-42) Parameter 'client_id' not present or present multiple times in the HTTP request parameters
2024-06-06 08:40:56,605 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="null", userId="null", ipAddress="41.216.98.178", error="invalid_request"
2024-06-06 08:41:52,789 WARN  [org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor] (executor-thread-42) Parameter 'client_id' not present or present multiple times in the HTTP request parameters
2024-06-06 08:41:52,790 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="null", userId="null", ipAddress="41.216.98.178", error="invalid_request"
2024-06-06 08:58:57,966 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="0f279dc9-88c4-4e6c-a203-531dbba5832c", ipAddress="82.64.92.162", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="Julien"
2024-06-06 08:59:44,026 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="0f279dc9-88c4-4e6c-a203-531dbba5832c", ipAddress="82.64.92.162", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="Julien"
2024-06-06 08:59:50,260 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="0f279dc9-88c4-4e6c-a203-531dbba5832c", ipAddress="82.64.92.162", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="Julien"
2024-06-06 08:59:58,304 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="0f279dc9-88c4-4e6c-a203-531dbba5832c", ipAddress="82.64.92.162", error="invalid_user_credentials", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="Julien"
2024-06-06 09:13:54,313 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="null", ipAddress="41.216.98.178", error="invalid_request", auth_method="oauth_credentials", grant_type="password", client_auth_method="client-secret"
2024-06-06 09:14:12,333 WARN  [org.keycloak.events] (executor-thread-42) type="REFRESH_TOKEN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="41.216.98.178", error="invalid_token", reason="Token is not active", grant_type="refresh_token", client_auth_method="client-secret"
2024-06-06 09:15:15,013 WARN  [org.keycloak.events] (executor-thread-49) type="LOGIN_ERROR", realmId="02f3ee47-c12f-4d2c-9dea-8c2802972a65", clientId="vizion-auth-client", userId="null", ipAddress="41.216.98.178", error="invalid_request", auth_method="oauth_credentials", grant_type="password", client_auth_method="client-secret"
2024-06-06 12:01:47,129 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-06 18:23:47,190 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-06 18:24:11,869 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-07 00:10:10,170 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-07 00:18:54,493 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-07 05:52:37,777 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-07 08:32:44,316 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-07 09:02:42,745 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-07 11:39:31,289 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-07 11:47:57,237 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-07 18:23:40,068 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-07 22:59:33,559 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-08 00:12:12,389 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-08 06:09:41,603 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-08 12:15:48,632 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-08 12:32:55,762 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-08 15:39:07,164 WARN  [org.keycloak.events] (executor-thread-91) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="90.12.36.85", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="19540f14-36ff-45b5-811c-38a6e998e2e5", username="PROXI"
2024-06-08 15:39:28,725 WARN  [org.keycloak.events] (executor-thread-91) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="90.12.36.85", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="19540f14-36ff-45b5-811c-38a6e998e2e5", username="PROXI"
2024-06-08 15:54:22,084 WARN  [org.keycloak.events] (executor-thread-91) type="LOGIN_ERROR", realmId="7d6b2542-986d-47b0-8854-2593f344141f", clientId="security-admin-console", userId="null", ipAddress="90.12.36.85", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="https://auth-test-v2.vizeo.eu/admin/master/console/", code_id="19540f14-36ff-45b5-811c-38a6e998e2e5", username="PROXI"
2024-06-08 16:34:42,539 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-08 17:52:15,398 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-09 00:05:19,727 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-09 01:02:10,751 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-09 06:13:40,926 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-09 06:50:01,699 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-09 12:02:54,369 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-09 17:58:14,377 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-09 20:05:54,963 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-10 00:13:30,627 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-10 00:20:42,884 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-10 01:15:41,575 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-10 02:44:46,782 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-10 05:45:51,739 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-10 10:08:22,913 WARN  [org.keycloak.models.utils.RepresentationToModel] (executor-thread-91) Using deprecated 'credentials' format in JSON representation for user 'TOTO'. It will be removed in future versions
2024-06-10 10:08:22,914 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-91) Uncaught server error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.keycloak.representations.idm.CredentialRepresentation.getHashIterations()" is null
	at org.keycloak.models.utils.RepresentationToModel.convertDeprecatedCredentialsFormat(RepresentationToModel.java:232)
	at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:745)
	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:152)
	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-10 11:20:30,304 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-10 12:01:50,322 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-10 17:44:39,620 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-10 23:46:04,098 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-11 02:32:44,170 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-11 06:10:30,940 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-11 07:03:58,950 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-11 11:47:21,767 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-11 18:23:36,948 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-11 18:35:18,820 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-11 20:52:01,709 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-11 20:52:28,224 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-11 20:52:43,361 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-12 00:03:47,370 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-12 01:45:31,833 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-12 05:59:35,308 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-12 10:03:14,300 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-12 11:46:15,443 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-12 18:03:34,399 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-12 23:50:33,555 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-13 00:21:02,211 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-13 00:59:21,622 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-13 15:26:03,963 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-13 22:16:50,643 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-14 04:54:55,821 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-14 05:20:05,328 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-14 05:51:18,570 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-14 09:58:55,470 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-14 20:18:37,633 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-15 02:24:08,058 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-15 09:58:29,421 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-15 10:41:47,817 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-16 00:56:41,845 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-16 02:34:44,417 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-16 10:07:45,585 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-16 11:21:36,435 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-16 16:45:04,619 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-17 01:23:51,613 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-114) Uncaught server error: java.lang.IllegalArgumentException: Failed to parse media type ${#context["com.opensymphony.xwork2.dispatcher.HttpServletResponse"].addHeader("Keyvalue",994*996)}.multipart/form-data
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:95)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:53)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:128)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:15)
	at jakarta.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at org.jboss.resteasy.reactive.server.jaxrs.HttpHeadersImpl.getMediaType(HttpHeadersImpl.java:88)
	at org.jboss.resteasy.reactive.server.jaxrs.ContainerRequestContextImpl.getMediaType(ContainerRequestContextImpl.java:125)
	at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:69)
	at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:43)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-17 01:23:55,017 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-114) Uncaught server error: java.lang.IllegalArgumentException: Failed to parse media type %{(#test='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#req=@org.apache.struts2.ServletActionContext@getRequest()).(#res=@org.apache.struts2.ServletActionContext@getResponse()).(#res.setContentType('text/html;charset=UTF-8')).(#res.getWriter().print('struts2_security_')).(#res.getWriter().print('check')).(#res.getWriter().flush()).(#res.getWriter().close())}
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:95)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:53)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:128)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:15)
	at jakarta.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at org.jboss.resteasy.reactive.server.jaxrs.HttpHeadersImpl.getMediaType(HttpHeadersImpl.java:88)
	at org.jboss.resteasy.reactive.server.jaxrs.ContainerRequestContextImpl.getMediaType(ContainerRequestContextImpl.java:125)
	at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:69)
	at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:43)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-17 01:27:33,014 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-17 04:23:06,983 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-17 06:01:45,021 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-17 21:47:28,452 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-18 01:02:48,130 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-2) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-18 11:40:45,324 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-19 00:09:38,238 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-4) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-19 03:56:29,915 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
2024-06-19 06:53:50,263 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-19 18:43:04,194 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-20 04:54:35,948 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-20 07:02:23,037 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-20 16:11:59,314 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-20 23:50:47,606 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-21 08:06:26,210 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-21 15:06:55,704 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-22 01:39:13,086 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-22 05:25:38,650 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-22 20:59:24,603 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-23 11:25:48,637 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-23 11:52:10,284 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-23 12:18:19,060 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-24 00:25:10,418 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-9) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-24 01:48:10,024 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router
2024-06-24 02:00:33,724 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-9) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-24 19:24:46,762 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-06-25 01:20:38,920 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-9) Unhandled exception in router
2024-06-25 10:39:03,012 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-06-26 00:08:16,542 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-26 01:50:59,785 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-8) Unhandled exception in router
2024-06-26 10:06:51,122 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-26 11:48:40,613 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-26 14:04:12,439 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-26 15:47:39,634 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-11) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-27 06:03:03,523 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-06-27 07:45:48,455 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-27 15:40:59,607 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-06-27 19:33:22,664 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router
2024-06-27 22:05:09,941 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-28 10:00:13,971 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-28 11:43:37,294 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-06-29 01:15:07,271 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-06-29 14:49:58,275 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-2) Unhandled exception in router
2024-06-30 06:23:29,708 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-07-01 08:30:10,202 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-10) Unhandled exception in router
2024-07-01 09:09:39,185 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-07-01 10:35:58,690 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-6) Unhandled exception in router
2024-07-01 11:05:01,581 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-7) Unhandled exception in router
2024-07-01 11:05:26,369 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-07-01 11:05:38,996 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-3) Unhandled exception in router
2024-07-01 18:13:10,366 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-11) Unhandled exception in router
2024-07-01 20:53:18,329 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-07-02 07:08:50,487 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-5) Unhandled exception in router
2024-07-04 04:24:07,265 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-9) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-04 15:16:09,364 WARN  [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-8) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-05 01:48:34,124 ERROR [io.vertx.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router
